version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "sqlite:////app/data/tailor.db"
      SECRET_KEY: "change-me"
      USE_OLLAMA: "false"
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  backend_data:
